# Generated by Django 6.1 on 2026-09-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_name', models.CharField(default='DOCCURE', max_length=200)),
                ('website_logo', models.ImageField(blank=True, null=True, upload_to='website/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='website/')),
            ],
        ),
    ]
