# Generated by Django 6.0.5 on 2026-08-10 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docter', '0002_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableTiming',
        ),
    ]
