# Generated by Django 6.1 on 2026-08-27 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_docter_designation_docter_display_name_docter_email_and_more'),
        ('docter', '0003_delete_availabletiming'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_name', models.CharField(max_length=200)),
                ('record_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('report', models.FileField(blank=True, upload_to='medical_records/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.docter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient')),
            ],
        ),
    ]
