# Generated by Django 6.0.5 on 2026-08-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_docter_designation_docter_display_name_docter_email_and_more'),
        ('patient', '0003_vital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vital',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient'),
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_doctors', to='app1.docter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='app1.patient')),
            ],
        ),
    ]
