# Generated by Django 6.0.5 on 2026-08-25 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_docter_designation_docter_display_name_docter_email_and_more'),
        ('patient', '0004_alter_vital_patient_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='docter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.docter'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.patient'),
        ),
    ]
