# Generated by Django 6.0.5 on 2026-08-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_patient_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='docter',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docter',
            name='display_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='languages',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='docter',
            name='last_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='membership_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='docter',
            name='membership_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='docter',
            name='phone',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docter',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/'),
        ),
    ]
