# Generated by Django 6.1 on 2026-09-04 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
