# Generated by Django 6.1 on 2026-09-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_product_discount_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
